# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set-up OCaml 4.13.1
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.1

      - run: opam pin add Lama https://github.com/PLTools/Lama.git\#1.20 --no-action
      - run: opam depext Lama --yes --with-test
      - run: opam install Lama --yes
      - run: eval $(opam env)

      - name: Perfomance Test
        run: opam exec -- make perfomance

      - name: Regression Test
        run: opam exec -- make test
